#############################################################################
# Makefile for building: build
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  build.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake CONFIG+=release -o Makefile build.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = build1.0.0
DISTDIR = /home/gulfam/Desktop/El-MAVEN/ElMaven/.tmp/build1.0.0
SUBTARGETS    =  \
		sub-3rdparty \
		sub-src \
		sub-tests-MavenTests \
		sub-CrashReporter


sub-3rdparty-qmake_all:  FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile
	cd 3rdparty/ && $(MAKE) -f Makefile qmake_all
sub-3rdparty: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile
sub-3rdparty-make_first-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-3rdparty-make_first: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-3rdparty-all-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-3rdparty-all: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-3rdparty-clean-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-3rdparty-clean: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-3rdparty-distclean-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-3rdparty-distclean: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-3rdparty-install_subtargets-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-3rdparty-install_subtargets: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-3rdparty-uninstall_subtargets-ordered: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-3rdparty-uninstall_subtargets: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-qmake_all: sub-3rdparty-qmake_all FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: sub-3rdparty-make_first-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: sub-3rdparty-all-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: sub-3rdparty-clean-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: sub-3rdparty-distclean-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: sub-3rdparty-install_subtargets-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: sub-3rdparty-uninstall_subtargets-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-MavenTests-qmake_all: sub-src-qmake_all FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile
	cd tests/MavenTests/ && $(MAKE) -f Makefile qmake_all
sub-tests-MavenTests: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile
sub-tests-MavenTests-make_first-ordered: sub-src-make_first-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-MavenTests-make_first: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-MavenTests-all-ordered: sub-src-all-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-MavenTests-all: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-MavenTests-clean-ordered: sub-src-clean-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-MavenTests-clean: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-MavenTests-distclean-ordered: sub-src-distclean-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-MavenTests-distclean: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-MavenTests-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-MavenTests-install_subtargets: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-MavenTests-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-MavenTests-uninstall_subtargets: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-CrashReporter-qmake_all: sub-tests-MavenTests-qmake_all FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile
	cd CrashReporter/ && $(MAKE) -f Makefile qmake_all
sub-CrashReporter: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile
sub-CrashReporter-make_first-ordered: sub-tests-MavenTests-make_first-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-CrashReporter-make_first: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile 
sub-CrashReporter-all-ordered: sub-tests-MavenTests-all-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-CrashReporter-all: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile all
sub-CrashReporter-clean-ordered: sub-tests-MavenTests-clean-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-CrashReporter-clean: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile clean
sub-CrashReporter-distclean-ordered: sub-tests-MavenTests-distclean-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-CrashReporter-distclean: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile distclean
sub-CrashReporter-install_subtargets-ordered: sub-tests-MavenTests-install_subtargets-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-CrashReporter-install_subtargets: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile install
sub-CrashReporter-uninstall_subtargets-ordered: sub-tests-MavenTests-uninstall_subtargets-ordered  FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-CrashReporter-uninstall_subtargets: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: build.pro .qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		build.pro
	$(QMAKE) CONFIG+=release -o Makefile build.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
build.pro:
qmake: FORCE
	@$(QMAKE) CONFIG+=release -o Makefile build.pro

qmake_all: sub-3rdparty-qmake_all sub-src-qmake_all sub-tests-MavenTests-qmake_all sub-CrashReporter-qmake_all FORCE

make_first: sub-3rdparty-make_first-ordered sub-src-make_first-ordered sub-tests-MavenTests-make_first-ordered sub-CrashReporter-make_first-ordered  FORCE
all: sub-3rdparty-all-ordered sub-src-all-ordered sub-tests-MavenTests-all-ordered sub-CrashReporter-all-ordered  FORCE
clean: sub-3rdparty-clean-ordered sub-src-clean-ordered sub-tests-MavenTests-clean-ordered sub-CrashReporter-clean-ordered  FORCE
distclean: sub-3rdparty-distclean-ordered sub-src-distclean-ordered sub-tests-MavenTests-distclean-ordered sub-CrashReporter-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-3rdparty-install_subtargets-ordered sub-src-install_subtargets-ordered sub-tests-MavenTests-install_subtargets-ordered sub-CrashReporter-install_subtargets-ordered FORCE
uninstall_subtargets: sub-3rdparty-uninstall_subtargets-ordered sub-src-uninstall_subtargets-ordered sub-tests-MavenTests-uninstall_subtargets-ordered sub-CrashReporter-uninstall_subtargets-ordered FORCE

sub-3rdparty-check_ordered:
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile check
sub-src-check_ordered: sub-3rdparty-check_ordered 
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile check
sub-tests-MavenTests-check_ordered: sub-src-check_ordered 
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile check
sub-CrashReporter-check_ordered: sub-tests-MavenTests-check_ordered 
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -f Makefile check
check: sub-3rdparty-check_ordered sub-src-check_ordered sub-tests-MavenTests-check_ordered sub-CrashReporter-check_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-3rdparty-distdir sub-src-distdir sub-tests-MavenTests-distdir sub-CrashReporter-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf build.pro $(DISTDIR)/

sub-3rdparty-distdir: FORCE
	@test -d 3rdparty/ || mkdir -p 3rdparty/
	cd 3rdparty/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/3rdparty/3rdparty.pro CONFIG+=release -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/3rdparty

sub-src-distdir: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/src/src.pro CONFIG+=release -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/src

sub-tests-MavenTests-distdir: FORCE
	@test -d tests/MavenTests/ || mkdir -p tests/MavenTests/
	cd tests/MavenTests/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/tests/MavenTests/MavenTests.pro CONFIG+=release -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tests/MavenTests

sub-CrashReporter-distdir: FORCE
	@test -d CrashReporter/ || mkdir -p CrashReporter/
	cd CrashReporter/ && ( test -e Makefile || $(QMAKE) /home/gulfam/Desktop/El-MAVEN/ElMaven/CrashReporter/CrashReporter.pro CONFIG+=release -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/CrashReporter

