######################################################################
# Automatically generated by qmake (3.0) Wed Aug 3 12:57:51 2016
######################################################################

CONFIG += testlib
TEMPLATE = app
TARGET = MavenTests
QT += testlib

# Input
SOURCES += tst_maventeststest.cpp
