CLI_CONFIGS_PATH = "data/"
CONFIG_EXTENSION = "xml"
PEAK_DETECTOR_PATH = "../../bin/peakdetector.app/Contents/MacOS/peakdetector"
OUTPUT_PATH = "tmp/"
RESULT_DIR = "results/"
PLOT_RESULT = "Results.html"
OUTPUT_FILE_NAME_CSV = "compounds.csv"
UNIQUE_IDENTIFIERS = ["compoundId", "compound", "formula", "goodPeakCount"]
SAMPLE_LIST = ["testsample_1", "testsample_2", "testsample_3"]
OUTPUT_FILE_NAME_JSON = "compounds.json"
CSV_EXTENSION = ".csv"
JSON_EXTENSION = ".json"