CLI_CONFIGS_PATH = "data/"
CONFIG_EXTENSION = "xml"
PEAK_DETECTOR_PATH = "../../../build/bin/peakdetector"
OUTPUT_PATH = "tmp/"
RESULT_DIR = "results/"
PLOT_RESULT = "Results.html"
OUTPUT_FILE_NAME = "compounds.csv"
UNIQUE_IDENTIFIERS = ["compoundId", "compound", "formula", "goodPeakCount"]
SAMPLE_LIST = ["testsample_1", "testsample_2", "testsample_3"]