ASCII = "ascii"
AUTOMATED_INTENSITY = "Automated Intensity"
AUTOMATED_INTENSITY_TEXT = " <br>Automated Intensity : "
CAPS_INTENSITY = "Intensity"
COMPOUND_NAME = "compoundName"
DICT_DIFF_RETURN_MESSAGE = "No difference in method files from both the datasets"
EIC = "eic"
GROUP_ID = "groupId"
INTENSITY = "intensity"
LINES = 'lines'
MANUAL_INTENSITY = "Manual Intensity"
MANUAL_INTENSITY_TEXT = " <br>Manual Intensity : "
MARKERS = 'markers'
PEAK_INTENSITY = "peakIntensity"
PEAK_MZ = "peakMz"
PEAKS = "peaks"
PEAK_DETECTION_SETTINGS = 'PeakDetectionSettings'
RT = "rt"
SAMPLE_NAME = "sampleName"
SAMPLE_TIME = "Sample time"
SETTINGS = 'Settings'
SPLIT_CHARACTER = "@"
SAMPLE_TEXT = "Sample Name : "
TEXT = "text"
ZERO = 0
comparatername = "comparaterName"
compoundId = "compoundId"
tagstring = "tagString"
comparatername = "comparaterName"
meanMz = "meanMz"
meanRt = "meanRt"
one = 1
unique_identifier_man = "unique_identifier_man"
unique_identifier_auto = "unique_identifier_auto"
corr_coff = "corr_coff"
p_val = "p_val"
logfc_auto_to_man = "logfc_auto_to_man"
by_delta_rt_and_mz = 1
na = 'NA'
by_n_closest_rt_and_mz = 2
by_closest_and_delta_rt_and_mz = 3
avg_intensity_man = "avg_intensity_man"
avg_intensity_auto = "avg_intensity_auto"
cor_plot_x_title = "Log of Average intensity automated curation"
cor_plot_y_title = "Log of Average intensity Manual curation"
cor_plot_main_title = "Manual vs Automated"
cor_plot_color_scale = 'Viridis'
cor_plot_datapoint_size = '16'
cor_plot_hover_mode = "closest"
log2_fc = "Log2FC"
neg_log10_pval = "-Log10(P-val)"
wilcox_plot_title = "Wilcox Plot"
orange_color = "orange"
groupid = "groupId"
peaks = "peaks"
peakIntensity = "peakIntensity"
by_n_closest_rt = "by n closest rt"
by_n_closest_mz = "by n closest mz"
br = "<br>"
COMPOUND = "compound"
CSV_SCATTER_PLOT_TITLE = "ScatterPlot"
CSV_SCATTER_PLOT_X_TITLE = "Log Intensities of metabolites"
CSV_SCATTER_PLOT_Y_TITLE = "Log Intensities of metabolites"
RESULT_DIR = "results/"
PLOT_RESULT = "Results.html"
SAMPLE_LIST = ["testsample_1", "testsample_2", "testsample_3"]
